### ISSUE TITLE
listNagiosObjects gives error with undefined index

### ISSUE THREAD

**Issue by rverchere** [EyesOfNetworkCommunity/eonapi#2]
When trying to call listNagiosObjects  I have an the following error:

```
$ curl -X POST -k -i 'https://127.0.0.1/eonapi/listNagiosObjects?&username=admin&apiKey=deadbeef
```

Result:

```
Slim Application Error

The application could not run because of the following error:
Details
Type: ErrorException
Code: 8
Message: Undefined index: object
File: /srv/eyesofnetwork/eonapi-git/html/api/index.php
Line: 60
Trace

#0 /srv/eyesofnetwork/eonapi-git/html/api/index.php(60): Slim\Slim::handleErrors(8, 'Undefined index...', '/srv/eyesofnetw...', 60, Array)
#1 [internal function]: {closure}()
#2 /srv/eyesofnetwork/eonapi-git/include/Slim/Route.php(462): call_user_func_array(Object(Closure), Array)
#3 /srv/eyesofnetwork/eonapi-git/include/Slim/Slim.php(1326): Slim\Route->dispatch()
#4 /srv/eyesofnetwork/eonapi-git/include/Slim/Middleware/Flash.php(85): Slim\Slim->call()
#5 /srv/eyesofnetwork/eonapi-git/include/Slim/Middleware/MethodOverride.php(92): Slim\Middleware\Flash->call()
#6 /srv/eyesofnetwork/eonapi-git/include/Slim/Middleware/PrettyExceptions.php(67): Slim\Middleware\MethodOverride->call()
#7 /srv/eyesofnetwork/eonapi-git/include/Slim/Slim.php(1271): Slim\Middleware\PrettyExceptions->call()
#8 /srv/eyesofnetwork/eonapi-git/html/api/index.php(92): Slim\Slim->run()
#9 {main}
```

I guess "object" must be specified, but how?

listNagiosStates and listNagiosBackends are OK.

**Comment by EyesOfNetwork** [comment]
For example :

{
  "object": "services",
  "backendid": "0",
  "columns": ["description","state"],
  "filters": [
    "host_name = localhost",
    "description ~~ ^service_"
   ]

**Comment by rverchere** [comment]
Ok, it works better ;)

It would be great to have an error message if no parameters are sent on these requests.
